In [0]:
import os, shutil

In [0]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import os
import pickle
import random
import shutil
import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import drive
from PIL import Image
from sklearn.model_selection import train_test_split

In [0]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive

In [0]:
df = pd.read_csv('/content/gdrive/My Drive/bigdata/df_final4.csv')

In [0]:
numeric = ['year_of_birth', 'basic_metabolic_panel', 'compreh_metabolic_panel', 'lipid_panel','Hemoglobin; glycosylated (A1C)','Thyroid stimulating hormone (TSH)','Blood count; complete (CBC), automated (Hgb, Hct, RBC, WBC and platelet count) and automated differential WBC count','Prothrombin time', 'Electrocardiogram, routine ECG with at least 12 leads; interpretation and report only','Type II diabetes mellitus uncontrolled','drug_num','condition_num', 'procedure_num']

In [0]:
df.head(5)

   Unnamed: 0  Unnamed: 0.1  ...         condition_type_concept_id  procedure_num
0           0             0  ...  Outpatient header - 1st position            1.0
1           1             1  ...  Outpatient header - 1st position            3.0
2           2             2  ...  Outpatient header - 1st position          150.0
3           3             3  ...  Outpatient header - 1st position          150.0
4           4             4  ...  Outpatient header - 1st position            1.0

[5 rows x 42 columns]

In [0]:
percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})
missing_value_df

                                                                                          column_name  percent_missing
Unnamed: 0                                                                                 Unnamed: 0         0.000000
Unnamed: 0.1                                                                             Unnamed: 0.1         0.000000
person_id                                                                                   person_id         0.000000
year_of_birth                                                                           year_of_birth         0.000000
gender_concept_id                                                                   gender_concept_id         0.000000
ethnicity_concept_id                                                             ethnicity_concept_id         0.000000
race_concept_id                                                                       race_concept_id        14.322680
death_type_concept_id                                                           death_type_concept_id         0.000000
death                                                                                           death         0.000000
basic_metabolic_panel                                                           basic_metabolic_panel        45.157558
compreh_metabolic_panel                                                       compreh_metabolic_panel        31.820161
lipid_panel                                                                               lipid_panel        37.658460
hepatic_func_panel                                                                 hepatic_func_panel        67.564037
Urinalysis_with_microscopy                                                 Urinalysis_with_microscopy        56.679895
Urinalysis_without_microscopy                                           Urinalysis_without_microscopy        66.338654
Creatine kinase (CK), (CPK); total                                 Creatine kinase (CK), (CPK); total        66.423249
Creatinine; blood                                                                   Creatinine; blood        67.559061
Hemoglobin; glycosylated (A1C)                                         Hemoglobin; glycosylated (A1C)        49.332570
Iron                                                                                             Iron        67.433413
Prostate specific antigen (PSA); total                         Prostate specific antigen (PSA); total        69.069331
Thyroid stimulating hormone (TSH)                                   Thyroid stimulating hormone (TSH)        44.803006
Blood count; complete (CBC), automated (Hgb, Hc...  Blood count; complete (CBC), automated (Hgb, H...        27.887737
Blood count; complete (CBC), automated (Hgb, Hc...  Blood count; complete (CBC), automated (Hgb, H...        63.775923
Prothrombin time                                                                     Prothrombin time        34.483659
Culture, bacterial; quantitative colony count, ...  Culture, bacterial; quantitative colony count,...        63.588072
Electrocardiogram, routine ECG with at least 12...  Electrocardiogram, routine ECG with at least 1...        57.700011
Electrocardiogram, routine ECG with at least 12...  Electrocardiogram, routine ECG with at least 1...        62.284314
Electrocardiogram, routine ECG with at least 12...  Electrocardiogram, routine ECG with at least 1...        46.017193
Type II diabetes mellitus uncontrolled                         Type II diabetes mellitus uncontrolled        49.985693
drug_num                                                                                     drug_num         0.000000
0.0                                                                                               0.0         0.000000
Walking disability                                                                 Walking disability         0.000000
Diabetic on insulin                                                               Diabetic on insulin         0.000000
High risk drug monitoring status                                     High risk drug monitoring status         0.000000
Ground mileage, per statute mile                                     Ground mileage, per statute mile         0.000000
Ambulance service, advanced life support, emerg...  Ambulance service, advanced life support, emer...         0.000000
Ambulance service, basic life support, non-emer...  Ambulance service, basic life support, non-eme...         0.000000
Ambulance service, basic life support, emergenc...  Ambulance service, basic life support, emergen...         0.000000
Low osmolar contrast material, 300-399 mg/ml io...  Low osmolar contrast material, 300-399 mg/ml i...         0.000000
Vaccine required                                                                     Vaccine required         0.000000
Postoperative care                                                                 Postoperative care         0.000000
H/O: artificial joint                                                           H/O: artificial joint         0.000000
History of renal transplant                                               History of renal transplant         0.000000
H/O: artificial eye lens                                                     H/O: artificial eye lens         0.000000
H/O: artificial heart valve                                               H/O: artificial heart valve         0.000000
Dialysis finding                                                                     Dialysis finding         0.000000
Family history of clinical finding                                 Family history of clinical finding         0.000000
Aftercare                                                                                   Aftercare         0.000000
History of clinical finding in subject                         History of clinical finding in subject         0.000000
Cardiac pacemaker in situ                                                   Cardiac pacemaker in situ         0.000000
condition_num                                                                           condition_num         0.000000
condition_type_concept_id                                                   condition_type_concept_id         0.000000
procedure_num                                                                           procedure_num         0.000000

In [0]:
dropcol0 = missing_value_df[missing_value_df['percent_missing']> 50]['column_name']

In [0]:
for i in numeric:
  if i in dropcol0:
     numeric.remove(i)

In [0]:
df = df.drop(dropcol0, axis = 1)
#df = df.drop('death_type_concept_id', axis = 1)

In [0]:
df.head()

   Unnamed: 0  Unnamed: 0.1  ...         condition_type_concept_id  procedure_num
0           0             0  ...  Outpatient header - 1st position            1.0
1           1             1  ...  Outpatient header - 1st position            3.0
2           2             2  ...  Outpatient header - 1st position          150.0
3           3             3  ...  Outpatient header - 1st position          150.0
4           4             4  ...  Outpatient header - 1st position            1.0

[5 rows x 53 columns]

In [0]:
df = df.replace(to_replace = 'none', value = np.nan)

In [0]:
df[numeric] = df[numeric].apply(pd.to_numeric)

In [0]:
percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})
missing_value_df

                                                                                          column_name  percent_missing
Unnamed: 0                                                                                 Unnamed: 0         0.000000
Unnamed: 0.1                                                                             Unnamed: 0.1         0.000000
person_id                                                                                   person_id         0.000000
year_of_birth                                                                           year_of_birth         0.000000
gender_concept_id                                                                   gender_concept_id         0.000000
ethnicity_concept_id                                                             ethnicity_concept_id         0.000000
race_concept_id                                                                       race_concept_id        14.322680
death_type_concept_id                                                           death_type_concept_id         0.000000
death                                                                                           death         0.000000
basic_metabolic_panel                                                           basic_metabolic_panel        45.157558
compreh_metabolic_panel                                                       compreh_metabolic_panel        31.820161
lipid_panel                                                                               lipid_panel        37.658460
Hemoglobin; glycosylated (A1C)                                         Hemoglobin; glycosylated (A1C)        49.332570
Thyroid stimulating hormone (TSH)                                   Thyroid stimulating hormone (TSH)        44.803006
Blood count; complete (CBC), automated (Hgb, Hc...  Blood count; complete (CBC), automated (Hgb, H...        27.887737
Prothrombin time                                                                     Prothrombin time        34.483659
Electrocardiogram, routine ECG with at least 12...  Electrocardiogram, routine ECG with at least 1...        46.017193
Type II diabetes mellitus uncontrolled                         Type II diabetes mellitus uncontrolled        49.985693
drug_num                                                                                     drug_num         0.000000
0.0                                                                                               0.0         0.000000
Walking disability                                                                 Walking disability         0.000000
Diabetic on insulin                                                               Diabetic on insulin         0.000000
High risk drug monitoring status                                     High risk drug monitoring status         0.000000
Ground mileage, per statute mile                                     Ground mileage, per statute mile         0.000000
Ambulance service, advanced life support, emerg...  Ambulance service, advanced life support, emer...         0.000000
Ambulance service, basic life support, non-emer...  Ambulance service, basic life support, non-eme...         0.000000
Ambulance service, basic life support, emergenc...  Ambulance service, basic life support, emergen...         0.000000
Low osmolar contrast material, 300-399 mg/ml io...  Low osmolar contrast material, 300-399 mg/ml i...         0.000000
Vaccine required                                                                     Vaccine required         0.000000
Postoperative care                                                                 Postoperative care         0.000000
H/O: artificial joint                                                           H/O: artificial joint         0.000000
History of renal transplant                                               History of renal transplant         0.000000
H/O: artificial eye lens                                                     H/O: artificial eye lens         0.000000
H/O: artificial heart valve                                               H/O: artificial heart valve         0.000000
Dialysis finding                                                                     Dialysis finding         0.000000
Family history of clinical finding                                 Family history of clinical finding         0.000000
Aftercare                                                                                   Aftercare         0.000000
History of clinical finding in subject                         History of clinical finding in subject         0.000000
Cardiac pacemaker in situ                                                   Cardiac pacemaker in situ         0.000000
condition_num                                                                           condition_num         0.000000
condition_type_concept_id                                                   condition_type_concept_id         0.000000
procedure_num                                                                           procedure_num         0.000000

In [0]:
dropcol = missing_value_df[missing_value_df['percent_missing']> 50]['column_name']
dropcol = list(dropcol)
dropcol

['hepatic_func_panel',
 'Urinalysis_with_microscopy',
 'Urinalysis_without_microscopy',
 'Creatine kinase (CK), (CPK); total',
 'Creatinine; blood',
 'Iron',
 'Prostate specific antigen (PSA); total',
 'Blood count; complete (CBC), automated (Hgb, Hct, RBC, WBC and platelet count)',
 'Culture, bacterial; quantitative colony count, urine',
 '2313814.0',
 'Electrocardiogram, routine ECG with at least 12 leads; tracing only, without interpretation and report']

In [0]:
imcomplete = [i for i in numeric if i not in dropcol]

In [0]:
df = df.drop(dropcol, axis = 1)

In [0]:
numeric

### resampling

In [0]:
from sklearn.utils import resample

### impute

In [0]:
def imput_num(var):
    a = knn_impute(target=df[var], attributes=df.drop([var, 'Unnamed: 0', 'person_id'], 1),
                                    aggregation_method="median", k_neighbors=10, numeric_distance='euclidean',
                                    categorical_distance='hamming', missing_neighbors_threshold=0.8)
    print(a)

In [0]:
c = df[numeric].fillna(df[numeric].mean(), inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6287: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [0]:
df[numeric].head()

In [0]:
from fancyimpute import KNN 
df[numeric] = KNN(k=5).fit_transform(X_incomplete)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
Using TensorFlow backend.

In [0]:
X = df.drop(['death'], axis = 1)
Y = df['death']
X = pd.get_dummies(X, prefix_sep='_')
Y = LabelEncoder().fit_transform(Y)
X = StandardScaler().fit_transform(X)

In [0]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, 
                                                        test_size = 0.30, 
                                                        random_state = 101)

not_death = X[X.death==0.0]
death = X[X.death==1.0]

# upsample minority
d_upsampled = resample(death,
                          replace=True, # sample with replacement
                          n_samples=len(not_death), # match number in majority class
                          random_state=27) # reproducible results

# combine majority and upsampled minority
upsampled = pd.concat([not_death, d_upsampled])

# check new class counts
upsampled.death.value_counts()

###Random Forest

In [0]:
def forest_test(X, Y):
    X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, 
                                                        test_size = 0.30, 
                                                        random_state = 101)
    start = time.process_time()
    trainedforest = RandomForestClassifier(n_estimators=700).fit(X_Train,Y_Train)
    print(time.process_time() - start)
    predictionforest = trainedforest.predict(X_Test)
    print(confusion_matrix(Y_Test,predictionforest))
    print(classification_report(Y_Test,predictionforest))

In [0]:
forest_test(X , Y)

1985.2819875960001
[[23852     0]
 [    0   263]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     23852
           1       1.00      1.00      1.00       263

    accuracy                           1.00     24115
   macro avg       1.00      1.00      1.00     24115
weighted avg       1.00      1.00      1.00     24115

###PCA

In [0]:
from sklearn.decomposition import PCA

pca = PCA(n_components=8)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca, columns = ['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8'])
PCA_df = pd.concat([PCA_df, df['death']], axis = 1)
PCA_df['death'] = LabelEncoder().fit_transform(PCA_df['death'])
PCA_df.head()

        PC1        PC2       PC3       PC4  ...       PC6       PC7       PC8  death
0 -4.700756   1.528240 -0.140908  0.319622  ...  0.169078  0.123826  0.208492      0
1  3.669078  -1.509197 -0.142876  1.488316  ...  2.186720 -1.032708  3.859712      0
2 -3.030353  -1.294793  0.199160  0.246035  ... -0.096346  0.360228  0.182171      0
3 -0.970225  12.436108  1.221352 -0.427463  ...  0.219713  0.868811  1.171532      0
4 -4.110703  -1.405570 -0.160245  0.037347  ... -0.227424 -0.386865  0.511282      0

[5 rows x 9 columns]

In [0]:
forest_test(X_pca, Y)

31.41995460299995
[[23852     0]
 [    1   262]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     23852
           1       1.00      1.00      1.00       263

    accuracy                           1.00     24115
   macro avg       1.00      1.00      1.00     24115
weighted avg       1.00      1.00      1.00     24115

In [0]:
figure(num=None, figsize=(8, 8), dpi=80, facecolor='w', edgecolor='k')

classes = [0, 1, 2, 3, 4, 5, 6, 7]
colors = ['red', 'blue', 'yellow', 'green', 'black', 'pink', 'purple', 'oriange']
for clas, color in zip(classes, colors):
    plt.scatter(PCA_df.loc[PCA_df['class'] == clas, 'PC1'], 
                PCA_df.loc[PCA_df['class'] == clas, 'PC2'], 
                c = color)
    
plt.xlabel('Principal Component 1', fontsize = 12)
plt.ylabel('Principal Component 2', fontsize = 12)
plt.title('2D PCA', fontsize = 15)
plt.legend(['Poisonous', 'Edible'])
plt.grid()

### deep learning

In [0]:
try:
  %tensorflow_version 2.x
except Exception:
  pass

In [0]:
import tensorflow as tf
print(tf.__version__)

In [0]:
from tensorflow.keras.layers import Dense, Flatten 
from tensorflow.keras import Model
import matplotlib.pyplot as plt

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(64, activation='relu')
])
  tf.keras.layers.Dense(10, activation='relu')
])
  tf.keras.layers.Dense(1, activation='signoid')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

In [0]:
def plot(history):
  history = model.fit()
  
  # The history object contains results on the training and test
  # sets for each epoch
  acc = history.history['accuracy']
  val_acc = history.history['val_accuracy']
  loss = history.history['loss']
  val_loss = history.history['val_loss']

  # Get the number of epochs
  epochs = range(len(acc))

  plt.title('Training and validation accuracy')
  plt.plot(epochs, acc, color='blue', label='Train')
  plt.plot(epochs, val_acc, color='orange', label='Val')
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend()

  _ = plt.figure()
  plt.title('Training and validation loss')
  plt.plot(epochs, loss, color='blue', label='Train')
  plt.plot(epochs, val_loss, color='orange', label='Val')
  plt.xlabel('Epoch')
  plt.ylabel('Loss')
  plt.legend()
  
plot(history)

In [0]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', 
                        input_shape=(IMG_SIZE, IMG_SIZE, 3)))
model.add(layers.MaxPooling2D(pool_size = (2,2)))
### TODO: your code here
# Add another pair of Conv2d and MaxPoolin2dD layers
# As the depth of the network increases, the images
# become smaller, and you can afford to use more 
# filters in each layer
model.add(layers.Conv2D(64, (3, 3), activation = 'relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)))
model.add(layers.MaxPooling2D(pool_size = (2,2)))